# Generated by Django 4.1.5 on 2023-01-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDeTarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('descricao', models.CharField(max_length=255)),
                ('data_inicio', models.DateTimeField()),
                ('data_de_encerramento', models.DateTimeField()),
            ],
        ),
    ]
